config/routes.rb
Rails.application.routes.draw do
	root to: 'users#home'
  devise_for :users
  resources :users, except: :create do
    collection do
      get :home
    end
  end
  post 'create_user' => 'users#create', as: :create_user      
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  ROLE = ['Admin', 'User']
	ROLE.each do |role|
		define_method "#{role.downcase}?" do
			type == role
		end
	end

end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :type])
  end

  def after_sign_in_path_for(resource)
	  home_users_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: %w(show edit destroy)
	before_action :check_authorization, except: :home
	def new
		@user = User.new
	end	

	def create
		@user = User.new(user_params)
		respond_to do |format|
			if @user.save
				format.html { redirect_to users_path, notice: 'User was successfully created.' }
	      format.json { render :index, status: :created, location: @user }
			else
				format.html { render :new }
	      format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	def index
		@users = User.where(type: nil)
	end

	def show; end
	def edit; end

	def update
		respond_to do |format|
			if current_user.update(user_params)
				bypass_sign_in(current_user)
				format.html { redirect_to users_path, notice: 'User was update created.' }
	      format.json { render :index, status: :created, location: current_user }
			else
				format.html { render :edit }
	      format.json { render json: current_user.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		if @user.destroy
			redirect_to users_path, notice: 'User was successfully deleted.'
		end
	end

	private 

	def check_authorization
		unless  current_user.admin?
			redirect_to home_users_path, alert: 'You are not authorized'
		end
	end

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:email, :name, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<div class="header">
  <div class="top-navbar">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <span class="aux-text d-none d-md-inline-block">
            <ul class="inline-links inline-links--style-1">
              <li>
                <i class="fa fa-envelope"></i>
                <a href="#">support@stanfordx.us</a>
              </li>
            </ul>
          </span>
        </div>
        <div class="col-md-6">
          <nav class="top-navbar-menu">
            <ul class="top-menu">
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
                <li>
                  <%= link_to 'Login', new_user_session_path  %>
                </li>
                <li>
                  <%= link_to 'Create account', new_user_registration_path  %>
                </li>
              <% end %>
              <% if user_signed_in? %>
                <li>
                  <a href="#" class="btn-st-trigger" data-effect="st-effect-1">
                  <i class="fa fa-ellipsis-h"></i>
                  </a>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar--bold navbar--bb-1px navbar-light bg-default ">
    <div class="container navbar-container">
      <%= link_to root_path, class: 'navbar-brand' do %>
        Stanford x
      <% end %>
      <div class="d-inline-block">
        <button class="navbar-toggler hamburger hamburger-js hamburger--spring" type="button" data-toggle="collapse" data-target="#navbar_main" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="hamburger-box">
        <span class="hamburger-inner"></span>
        </span>
        </button>
      </div>
      <div class="collapse navbar-collapse align-items-center justify-content-end" id="navbar_main">
        <div class="navbar-search-widget b-xs-bottom py-3 d-lg-none d-none">
          <form class="" role="form">
            <div class="input-group input-group-lg">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
              <button class="btn btn-base-3" type="button">Go!</button>
              </span>
            </div>
          </form>
        </div>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item dropdown megamenu">
              <%= link_to 'My Account', edit_accounts_path, class: 'nav-link' %>
            </li>
          <% end %>
          <% if current_user.present? && current_user.student? %>
            <li class="nav-item dropdown megamenu">
              <%= link_to 'All Experiences', experiences_job_applications_path, class: 'nav-link' %>
            </li>
          <% end %>

          <% if current_user.present? && current_user.employer? %>
            <li class="nav-item dropdown megamenu">
              <%= link_to 'My Experiences', filter_experience_jobs_path(status: false), class: 'nav-link' %>
            </li>
          <% end %>

          <% if current_user.present? && current_user.superadmin? %>
            <li class="nav-item dropdown megamenu">
              <%= link_to 'Admin Panel', admin_root_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestJob</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%#= render 'layouts/navbar' %>
    <div class="body-wrap">
      <div id="st-container" class="st-container">
        <div class="st-pusher">
          <div class="st-content">
            <div class="st-content-inner">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
  <%= render 'toastr_rails/flash' %>

</html>

app/views/users/_form.html.erb
<%= simple_form_for @user, url: create_user_path do |f| %>
	<%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.input :email%>
  <%= f.input :name%>
  <%= f.input :password%>
	<%= f.submit 'Create User', class: "btn btn-submit"%>
<% end %>

app/views/users/edit.html.erb
<div class="container">	
	<h1>Editing User <%= @user.name%></h1>

	<%= simple_form_for @user do |f| %>
		<%= f.error_notification %>
	  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
	  <%= f.input :email%>
	  <%= f.input :name%>
	  <%= f.input :password%>
		<%= f.submit 'Update User', class: 'btn btn-default'%>
	<% end %>
</div>

app/views/users/home.html.erb
<div class="col-md-6">
	<nav class="top-navbar-menu">
	  <ul class="top-menu">
	    <% if user_signed_in? %>
	      <li>
	        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'float-right' %>
	      </li>
      <% end %>
      <% if current_user.admin? %>
	      <li>
	        <%= link_to 'Create user', new_user_path, class: 'float-left'  %>
	      </li>
	      <li>
	        <%= link_to 'All Users', users_path, class: 'float-right'  %>
	      </li>
	    <% end %>
	  </ul>
	</nav>
</div>

<div class= "container">
	<div class= "row">
		Hello World
	</div>	
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="1">Email</th>
      <th colspan="1">Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td> <%= user.email %> </td>        
        <td> <%= user.name %></td>        
        <td><%= link_to 'Show', user_path(user) %>
        <%= link_to 'Edit', edit_user_path(user) %>
        <%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">
	<h1> Create User </h1>
	<%= render 'form', user: @user %>

	<%= link_to 'Back', home_users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<span> <%= @user.name %> </span>
<span> <%= @user.email %> </span>
<%= link_to 'Edit', edit_user_path(@user) %>